appeals/urls.py
"""
Copyright 2016 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static

import portal.urls
import main.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include(portal.urls)),
    url(r'^main/', include(main.urls)),
    url(r'^404/', TemplateView.as_view(template_name='404.html')),
    url(r'^$', RedirectView.as_view(url='/portal/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/api/urls.py
"""
Copyright 2016 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import url, include
from rest_framework import routers

from .views import AppealsViewSet


router = routers.DefaultRouter()
router.register(r'appeals', AppealsViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

main/urls.py
"""
Copyright 2016 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django.conf.urls import include, url

from . import views
from .api import urls

urlpatterns = [
    url(r'^create-appeal/$', views.create_appeal, name='create_appeal'),
    url(r'^appeals-list/$', views.appeals_list, name='appeals_list'),
    url(r'^appeal-details/$', views.appeal_details, name='appeal_details'),
    url(r'^appeals-journal/$', views.appeals_journal, name='appeals_journal'),
    url(r'^appeals-form9/$', views.appeals_form9, name='appeals_form9'),
    # url(r'^api/', include(urls)),
]

main/models.py
"""
Copyright 2016 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from importlib import import_module
from time import strftime
from datetime import date, timedelta

from django import forms
from django.db import models
from django.conf import settings


class Appeals(models.Model):
    """
    Обращения
    """

    LABELS = {
        'id':               '№',
        'date':             'Дата обращения',
        'time':             'Время обращения',
        'com_method':       'Способ обращения',
        'appeal_type':      'Тип обращения',
        'client_type':      'Вид потребителя',
        'legal_name':       'Офиц. наименование',
        'client':           'Контактное лицо',
        'com_info':         'Контактная информация',
        'object_name':      'Объект',
        'request':          'Содержит заявку',
        'finished_events':  'Выполненные мероприятия',
        'planned_events':   'Планируемые мероприятия',
    }

    COM_METHOD = (
        (1, 'В письменной форме'),
        (2, 'Через интернет'),
        (3, 'По телефону'),
        (4, 'Личное обращение'),
        (0, 'Прочее'),
    )

    APPEAL_TYPES = (
        (1, 'Оказание услуг по передаче электрической энергии'),
        (2, 'Осуществление технологического присоединения'),
        (3, 'Коммерческий учет электрической энергии'),
        (4, 'Качество обслуживания потребителей'),
        (5, 'Техническое обслуживание электросетевых объектов'),
        (0, 'Прочее'),
    )

    CLIENT_TYPES = (
        (1, 'Физическое лицо'),
        (2, 'Индивидуальный предприниматель'),
        (3, 'Юридическое лицо'),
    )

    REQUEST = (
        (0, 'не содержит'),
        (1, 'по технологическому присоединению'),
        (2, 'организация коммерческого учёта'),
    )

    class Meta:
        db_table = 'appeals'
        verbose_name = 'Обращения'
        verbose_name_plural = 'Обращения'

    date = models.DateField(verbose_name=LABELS['date'])
    time = models.TimeField(verbose_name=LABELS['time'])
    com_method = models.SmallIntegerField(choices=COM_METHOD, verbose_name=LABELS['com_method'])
    appeal_type = models.SmallIntegerField(choices=APPEAL_TYPES, verbose_name=LABELS['appeal_type'])
    client_type = models.SmallIntegerField(choices=CLIENT_TYPES, verbose_name=LABELS['client_type'])
    legal_name = models.CharField(max_length=255, null=True, blank=True, verbose_name=LABELS['legal_name'])
    client = models.CharField(max_length=255, null=True, blank=True, verbose_name=LABELS['client'])
    com_info = models.CharField(max_length=255, null=True, blank=True, verbose_name=LABELS['com_info'])
    object_name = models.CharField(max_length=255, null=True, blank=True, verbose_name=LABELS['object_name'])
    request = models.SmallIntegerField(choices=REQUEST, verbose_name=LABELS['request'])
    finished_events = models.TextField(null=True, blank=True, verbose_name=LABELS['finished_events'])
    planned_events = models.TextField(null=True, blank=True, verbose_name=LABELS['planned_events'])
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return "%06d" % self.pk


class AppealsForm(forms.ModelForm):
    """
    Форма добавления обращения
    """

    HELP_TEXTS = {
        'date':     'Введите дату в формате ДД.ММ.ГГГГ',
        'time':     'Введите время в формате ЧЧ:ММ',
        'com_info': 'Введите контактную информацию (номер телефона и т.п.)'
    }

    DATE_FORMATS = (
        '%d.%m.%Y',
    )

    TIME_FORMATS = (
        '%H:%M',
    )

    class Meta:
        model = Appeals
        fields = [
            'date', 'time',
            'com_method', 'appeal_type',
            'client_type', 'legal_name', 'client', 'com_info', 'object_name',
            'request', 'finished_events', 'planned_events',
        ]

    date = forms.DateField(
        label=Appeals.LABELS['date'],
        help_text=HELP_TEXTS['date'],
        input_formats=DATE_FORMATS,
        initial=lambda: strftime(AppealsForm.DATE_FORMATS[0]),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
        }), required=True
    )

    time = forms.TimeField(
        label=Appeals.LABELS['time'],
        help_text=HELP_TEXTS['time'],
        input_formats=TIME_FORMATS,
        initial=lambda: strftime(AppealsForm.TIME_FORMATS[0]),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
        }), required=True
    )

    com_method = forms.ChoiceField(
        label=Appeals.LABELS['com_method'],
        choices=Appeals.COM_METHOD,
        widget=forms.Select(attrs={
            'class': 'form-control selectpicker',
        }), required=True
    )

    appeal_type = forms.ChoiceField(
        label=Appeals.LABELS['appeal_type'],
        choices=Appeals.APPEAL_TYPES,
        widget=forms.Select(attrs={
            'class': 'form-control selectpicker',
        }), required=True
    )

    client_type = forms.ChoiceField(
        label=Appeals.LABELS['client_type'],
        choices=Appeals.CLIENT_TYPES,
        widget=forms.Select(attrs={
            'class': 'form-control selectpicker',
        }), required=True
    )

    legal_name = forms.CharField(
        label=Appeals.LABELS['legal_name'],
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }), required=False
    )

    client = forms.CharField(
        label=Appeals.LABELS['client'],
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }), required=False
    )

    com_info = forms.CharField(
        label=Appeals.LABELS['com_info'],
        help_text=HELP_TEXTS['com_info'],
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }), required=False
    )

    object_name = forms.CharField(
        label=Appeals.LABELS['object_name'],
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        }), required=False
    )

    request = forms.ChoiceField(
        label=Appeals.LABELS['request'],
        choices=Appeals.REQUEST,
        widget=forms.Select(attrs={
            'class': 'form-control selectpicker',
        }), required=True
    )

    finished_events = forms.CharField(
        label=Appeals.LABELS['finished_events'],
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 3,
        }), required=True
    )

    planned_events = forms.CharField(
        label=Appeals.LABELS['planned_events'],
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 3,
        }), required=False
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(AppealsForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        model = super(AppealsForm, self).save(commit=False)
        model.user = self.user
        if commit:
            model.save()
        return model


class AppealsReportForm(forms.Form):
    """
    Форма для отчётов по обращениям
    """

    LABELS = {
        'start_date':   'Начало периода',
        'end_date':     'Конец периода',
    }

    HELP_TEXTS = {
        'start_date':   'Введите дату в формате ДД.ММ.ГГГГ',
        'end_date':     'Введите дату в формате ДД.ММ.ГГГГ',
    }

    DATE_FORMATS = (
        '%d.%m.%Y',
    )

    start_date = forms.DateField(
        label=LABELS['start_date'],
        help_text=HELP_TEXTS['start_date'],
        input_formats=DATE_FORMATS,
        initial=lambda: AppealsReportForm._init_start_date(),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
        }), required=True
    )

    end_date = forms.DateField(
        label=LABELS['end_date'],
        help_text=HELP_TEXTS['end_date'],
        input_formats=DATE_FORMATS,
        initial=lambda: AppealsReportForm._init_end_date(),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
        }), required=True
    )

    @staticmethod
    def _init_start_date():
        previous_month = (
            date.today().replace(day=1) - timedelta(days=1)
        ).replace(day=1)
        return previous_month.strftime(AppealsReportForm.DATE_FORMATS[0])

    @staticmethod
    def _init_end_date():
        current_month = date.today().replace(day=1)
        return current_month.strftime(AppealsReportForm.DATE_FORMATS[0])


class AppealsReportFormWithDepartment(AppealsReportForm):
    """
    Форма для отчётов по обращениям с привязкой к отделу
    """

    LABELS = AppealsReportForm.LABELS.copy()
    LABELS.update({
        'department': 'Отдел',
    })

    DEPARTMENTS = (
        ('all', 'Все'),
        (2, 'ПТС'),
        (3, 'Электроинспекция')
    )

    department = forms.ChoiceField(
        label=LABELS['department'],
        choices=DEPARTMENTS,
        widget=forms.Select(attrs={
            'class': 'form-control selectpicker',
        }), required=True
    )

main/api/views.py
"""
Copyright 2016 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from rest_framework import viewsets

from ..models import Appeals
from .serializers import AppealsSerializer


class AppealsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Appeals.objects.all()
    serializer_class = AppealsSerializer

templates/main/appeal_details.html
<p><b>{{ data.LABELS.date }}: </b><span>{{ data.date|date:"d.m.Y" }}</span></p>
<p><b>{{ data.LABELS.time }}: </b><span>{{ data.time|time:"H:i" }}</span></p>
<p><b>{{ data.LABELS.com_method }}: </b><span>{{ data.get_com_method_display }}</span></p>
<p><b>{{ data.LABELS.appeal_type }}: </b><span>{{ data.get_appeal_type_display }}</span></p>
<p><b>{{ data.LABELS.client_type }}: </b><span>{{ data.get_client_type_display }}</span></p>

{% if data.legal_name %}<p><b>{{ data.LABELS.legal_name }}: </b><span>{{ data.legal_name }}</span></p>{% endif %}

<p><b>{{ data.LABELS.client }}: </b><span>{{ data.client }}</span></p>
<p><b>{{ data.LABELS.com_info }}: </b><span>{{ data.com_info }}</span></p>

{% if data.object_name %}<p><b>{{ data.LABELS.object_name }}: </b><span>{{ data.object_name }}</span></p>{% endif %}

<p><b>{{ data.LABELS.request }}: </b><span>{{ data.get_request_display }}</span></p>
<form>
    <div class="control-group">
        <label class="control-label" for="finished-events">{{ data.LABELS.finished_events }}:</label>
        <div class="controls">
            <textarea id="finished-events" class="form-control" readonly="readonly" rows="3">{{ data.finished_events }}</textarea>
        </div>
    </div>
</form>
<form>
    <div class="control-group">
        <label class="control-label" for="planned-events">{{ data.LABELS.planned_events }}:</label>
        <div class="controls">
            <textarea id="planned-events" class="form-control" readonly="readonly" rows="3">{{ data.planned_events }}</textarea>
        </div>
    </div>
</form>
<p><b>Зарегистрировал: </b><span>{{ data.user.first_name }} {{ data.user.last_name }}</span></p>

templates/main/appeals_form9.html
{% extends "forms.html" %}

{% block scripts %}
    <script type="text/javascript">

        $(document).ready(function () {

            var start_date = $('#id_start_date');
            var end_date = $('#id_end_date');

            start_date.datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY'
            });

            end_date.datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY'
            });


        });

    </script>
{% endblock %}

templates/main/appeals_journal.html
{% extends "forms.html" %}

{% block scripts %}
    <script type="text/javascript">

        $(document).ready(function () {

            var start_date = $('#id_start_date');
            var end_date = $('#id_end_date');

            start_date.datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY'
            });

            end_date.datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY'
            });


        });

    </script>
{% endblock %}

templates/main/appeals_list.html
{% extends "index.html" %}

{% block content %}

    <div class="pull-right" style="width: 260px">

        <form role="form" method="get" action="{% url 'appeals_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Поиск" name="q">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search"></span> Поиск
                    </button>
                </div>
            </div>
        </form>

    </div>

    <table class="table table-striped">

        <thead>
        <tr>
            <th class="col-md-1">&#X02116;</th>
            <th class="col-md-7">Потребитель</th>
            <th class="col-md-3">Контактная информация</th>
            <th class="col-md-1">Дата</th>
        </tr>
        </thead>
        <tbody>

        {% for item in items %}

            <tr>
                <td>
                    <a href="#" data-toggle="details" data-id="{{ item.pk }}">
                        {{ item }}
                    </a>
                </td>
                <td>
                    {% if item.legal_name and item.client %}
                        {{ item.legal_name }} ({{ item.client }})
                    {% endif %}

                    {% if item.legal_name and not item.client %}
                        {{ item.legal_name }}
                    {% endif %}

                    {% if item.client and not item.legal_name %}
                        {{ item.client }}
                    {% endif %}

                    {% if not item.legal_name and not item.client %}
                        Потребитель не указан
                    {% endif %}
                </td>
                <td>

                    {% if item.com_info %}
                        {{ item.com_info }}
                    {% else %}
                        Отсутствует
                    {% endif %}

                </td>
                <td>{{ item.date|date:"d.m.Y" }}</td>
            </tr>

        {% endfor %}

        </tbody>

    </table>

    {% with items as list %}
        {% include "paginator.html" %}
    {% endwith %}


{% endblock %}

{% block scripts %}
    <script type="application/javascript">

        $(document).ready(function () {

            $('a[data-toggle="details"]').detailsView({
                'title': 'Информация по обращению',
                callback: function (e, f) {
                    $.get("{% url 'appeal_details' %}", {'id': e.data('id')}, f);
                }
            });

        });

    </script>
{% endblock %}

templates/main/create_appeal.html
{% extends "forms.html" %}

{% block scripts %}
    <script type="application/javascript">

        $(document).ready(function () {


            var appealType = $('#id_appeal_type');

            appealType.val(localStorage['appeals.appeal_type']);

            appealType.change(function () {
                localStorage['appeals.appeal_type'] = $(this).val();
            });

            var clientType = $('#id_client_type');
            var legalName = $('#id_legal_name');

            var clientTypeFields = {
                2: legalName,
                3: legalName
            };

            clientType.extraFields({
                fields: clientTypeFields
            });

            var date = $('#id_date');

            date.datetimepicker({
                locale: 'ru',
                useCurrent: true,
                format: 'DD.MM.YYYY'
            });

        });

    </script>
{% endblock %}

templates/main/menu.html
<!-- Работа с обращениями -->
<li class="nav-header">Работа с обращениями</li>
<li><a href="{% url 'create_appeal' %}">Регистрация обращения</a></li>
<li><a href="{% url 'appeals_list' %}">Просмотр и поиск обращений</a></li>
<li><a href="{% url 'appeals_journal' %}">Журнал учёта обращений потребителей</a></li>
<li><a href="{% url 'appeals_form9' %}">Информация по обращениям потребителей (отчёт по форме №9)</a></li>